Resolves: #99, remove redundant typedefs
ofxa/openfx pull request #100
Opened 2022-11-08 17:31 UTC by fxtech

2022-11-10 23:30 UTC, garyo reviewed
I'm curious; why are these redundant? Isn't it nicer to be able to say (for example)
```c
OfxStandardColor color = kOfxStandardColourOverlayText;
```
than
```c
enum OfxStandardColor color = kOfxStandardColourOverlayText;
```
? Or is it considered more explicit for users to have to write out the `enum`? (And same for the structs)

What errors have folks seen?

2022-11-11 14:15 UTC, fxtech commented
It was my understanding that it was the extra unnecessary typedefs 
before the enum and struct declarations.

I don't think enum is used in front of variable declarations anywhere.

On 11/10/22 5:31 PM, GaryO wrote:
>
> ***@***.**** commented on this pull request.
>
> I'm curious; why are these redundant? Isn't it nicer to be able to say 
> (for example)
>
> OfxStandardColor color =kOfxStandardColourOverlayText;
>
> than
>
> |enum OfxStandardColor color = kOfxStandardColourOverlayText; |
>
> ? Or is it considered more explicit for users to have to write out the 
> |enum|? (And same for the structs)
>
> What errors have folks seen?
>
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/ofxa/openfx/pull/100#pullrequestreview-1176621703>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AAM64ASRWAY6CPGL65XZ57TWHWATRANCNFSM6AAAAAAR2SGWWE>.
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>
>

2022-11-11 15:20 UTC, john-paulsmith commented
This is a difference between C and C++. In C++, the typedef is unnecessary and might generate a compiler warning, but in pure C, @garyo's observation is correct.

2022-11-11 15:35 UTC, john-paulsmith requested changes
Revert these changes then change line 105 to `} OfxDrawTextAlignment;`.

2022-11-11 15:35 UTC, john-paulsmith commented on include/ofxDrawSuite.h
> -typedef enum OfxDrawTextAligment
This definition is the source of the original warning. The correct solution is not to remove the typedef, it's to add the missing type name after the closing parenthesis.

2022-11-11 15:46 UTC, john-paulsmith commented on include/ofxDrawSuite.h
> -typedef enum OfxDrawTextAligment
Also note the misspelling 'Aligment' in the enum definition. I believe this can be fixed because this typedef couldn't have actually been used as-is.

2022-12-06 17:49 UTC, revisionfx approved these changes

2022-12-06 18:15 UTC, merged